# Generated by Django 2.2.16 on 2021-02-25 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gbaragboscrumy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumygoals',
            name='goal_id',
            field=models.IntegerField(verbose_name=django.db.models.deletion.SET_NULL),
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='goal_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gbaragboscrumy.GoalStatus'),
        ),
    ]
