# Generated by Django 3.1.5 on 2021-02-01 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gbaragboscrumy', '0002_auto_20210201_2210'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScrumyGoals',
            new_name='ScrumyGoal',
        ),
    ]
