# Generated by Django 3.1.5 on 2021-02-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbaragboscrumy', '0002_auto_20210201_2210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrumygoals',
            options={'verbose_name_plural': 'ScrumyGoals'},
        ),
        migrations.AlterField(
            model_name='goalstatus',
            name='status_name',
            field=models.CharField(max_length=20),
        ),
    ]
