# Generated by Django 3.1.5 on 2021-02-01 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gbaragboscrumy', '0003_auto_20210201_2323'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScrumyGoal',
            new_name='ScrumyGoals',
        ),
    ]
