# Generated by Django 3.1.5 on 2021-02-02 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gbaragboscrumy', '0004_auto_20210201_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalstatus',
            name='status_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_user_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
