# Generated by Django 3.1.5 on 2021-02-02 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gbaragboscrumy', '0003_auto_20210202_1614'),
        ('gbaragboscrumy', '0005_auto_20210202_0803'),
    ]

    operations = [
    ]
